### ISSUE TITLE
(*) => 1 is reported "Missing Operand"

### ISSUE THREAD

**Issue by ZhuangQu** [thqby/vscode-autohotkey2-lsp#401] opened 2023-09-24 11:55 UTC
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/89310792/4798015d-4bb1-4e4f-8813-72e9ce459594)

**Comment by Descolada** [comment] 2023-09-24 12:38
Seems to be duplicate of #399 and should already be fixed (in GitHub only, not in the release version).

**Comment by ZhuangQu** [comment] 2023-09-25 05:46
Thank you for repairing it!

**Comment by ZhuangQu** [comment] 2023-09-25 05:46
Thank you for repairing it!

**Comment by Tomshiii** [comment] 2023-09-25 06:38
this issue doesn't appear to be completely solved with v2.1.8
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53557479/0e91c6b8-17e6-4a04-bba4-b04042439221)

or even from thqby's own webview2 script
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53557479/24f22d5c-20af-44e8-98aa-d614412c189d)

**Comment by fade2gray** [comment] 2023-09-25 11:44
@Tomshiii Remove the comma before the asterisk? `(guiCtrl *)` `(&k, &v *)`

**Comment by jollycoder** [comment] 2023-09-30 01:32
Same here:

![screenshot](https://i.imgur.com/Yytm829.png)

**Closed** 2023-10-04 14:26 UTC
